### ISSUE TITLE
[BUG/SDK] crashes the launcher and Settings-Apps

### ISSUE THREAD

**Issue by alsternerd** [c3nav/c3nav-android#12]
General information

App version: Latest
App source: F-Droid
Android Version: 6.0.1
Custom ROM: KonstaKANG LineageOS

Expected result

What is expected?
The app installs/upgrades without crashes parts of the system or the whole system.

What does happen instead?
It crashes the App-Launcher and Settings -> Apps Menu.
No uninstallation possible without ADB-access.
Steps to reproduce

Install latest version.

I got this same issue with mastalab, but without crashing the launcher, it could be the same root here:

The problems are the Android SDK Platform 25 and 26, with 27 (revision: 1) it should work like a charm.

Sources:
stom79/mastalab#31
andOTP/andOTP#76

What helped us figuring this out: https://forums.bitfire.at/topic/1603/replicant-lineage-1-9-1-causing-instant-crash-and-bootloops/15

**Comment by raphaelm** [comment]
Hi @alsternerd! Thank you for the bug report.

I struggle to see that this is a bug in this app, it seems pretty clear that this is a bug in the custom ROM, since at the time of the crash our app is not even running. Therefore, the bug cannot be in our app, but must be in the app metadata parser of the operating system. I suggest filing a bug with KonstaKANG LineageOS.

Besides, this app is not really maintained between January and November, since it is not much use while no Chaos Communication Congress is running. If this app will be in use again at 35c3, we'll upgrade the SDK platform version as part of our regular preparations and maintainance version for a new year.

**Comment by alsternerd** [comment]
The problem is not the app, but as I stated above the SDK-Version. The bug must then be withing LineageOS or the SDK provided by Google, with the SDK 27 and higher the bug is gone and everything installs fine.

The ROM, sadly, is no longer maintained. I installed this to test the F-Droid priviledge extension.

**Comment by raphaelm** [comment]
> The problem is not the app, but as I stated above the SDK-Version. The bug must then be withing LineageOS or the SDK provided by Google, with the SDK 27 and higher the bug is gone and everything installs fine.

Correct. However, it runs fine on all other ROMs, so I believe strongly in a bug in the ROM.

> PS. Why not debug software in between congress? :)

Because (a) this is not my software that has the problem, but the ROM and (b) because my day unfortunately only has 24 hours. :)
