### ISSUE TITLE
Suggestion: Deactivate logo animation on startup

### ISSUE THREAD

**Issue by CryptOwl** [c3nav/c3nav-android#20]
I like the c3nav logo animation in the Android. Problem is that it gets old really fast and keeps you from using the map for several seconds each time you launch the app. If not removed entirely I'd suggest to allow the user to deactivate it in the settings.

**Comment by codingcatgirl** [comment]
It actually doesn't keep you from using the map, because the map takes a while to load. Don't worry, you're not wasting time you wouldn't spend looking at a blank screen otherwise anyway.

Also, the logo isn't shown with every app launch. If it is, that's because your Android Device is removing the App from Memory completely which means it will take a while to load next time anyway and the logo does not waste your time.

**Comment by CryptOwl** [comment]
I also assumed the map is loading while the logo animation is playing. But it feels like the map of c3nav takes much less time to load in a regular browser (with cleared tabs/cache) than in the app. I can do some further testing tomorrow.
